apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-minikube
  annotations:
    ad.datadoghq.com/service.check_names: '["http_check"]'
    ad.datadoghq.com/service.init_configs: '[{}]'
    ad.datadoghq.com/service.instances: |
        [
          {
            "name": "My Nginx",
            "url": "http://%%host%%",
            "timeout": 1
          }
        ]
    ad.datadoghq.com/endpoints.check_names: '["nginx"]'
    ad.datadoghq.com/endpoints.init_configs: '[{}]'
    ad.datadoghq.com/endpoints.instances: |
        [
          {
             "name": "My Nginx Service Endpoints",
             "nginx_status_url": "http://%%host%%:%%port%%/nginx_status"
          }
        ]
    ad.datadoghq.com/endpoints.logs: '[{"source":"nginx","service":"webapp"}]'
  name: hello-minikube
  namespace: default
spec:
  clusterIP: 10.98.224.151
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31813
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-minikube
  sessionAffinity: None
  type: NodePort

